channels:
  - conda-forge
dependencies:
  - h5py
  - hoomd=2
  - ipywidgets>=7
  - joblib
  - jupyter
  - jupyterlab>=3
  - matplotlib>=3
  - mistune
  - nbconvert>=6
  - notebook>=6
  - numpy>=1.16
  - pandas>=1
  - pre-commit
  - python>=3
  - scikit-learn
  - signac-dashboard>=0.2
  - signac-flow>=0.15
  - signac>=1.6
  