channels:
  - conda-forge
dependencies:
  - hoomd=2
  - ipywidgets>=7
  - jupyterlab>=3
  - matplotlib>=3
  - mistune
  - nbconvert>=6
  - notebook>=6
  - numpy>=1.16
  - pandas>=1
  - python>=3
  - signac-flow>=0.12
  - signac>=1.6
